config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "top#index"
  resources :groups, only: [:new, :edit, :create, :update] do
    resources :messages, only: [:index, :create]
  end
  resources :users, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord

  validates :name, presence: true

  has_many :messages
  has_many :users, :through => :user_groups
  has_many :user_groups
  accepts_nested_attributes_for :users

end

app/models/message.rb
class Message < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  belongs_to :group
  mount_uploader :image , ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    validates :name, presence: true

  has_many :messages
  has_many :groups, :through => :user_groups
  has_many :user_groups

end

app/models/user_group.rb
class UserGroup < ApplicationRecord

  belongs_to :user
  belongs_to :group

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(groups_params)
    if @group.save
    redirect_to :root
    else
    render 'new'
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(groups_params)
    redirect_to :root
    else
    render 'edit'
    end
  end

  private
  def groups_params
    params.require(:group).permit(:name, :user_ids => [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @group = Group.find(params[:group_id])
    @groups = current_user.groups
    @message = Message.new
  end

  def create
    @message = Message.new(messages_params)

    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(params[:group_id]) }
        format.json
      end
    else
      redirect_to group_messages_path(params[:group_id]), alert: "メッセージを入力して下さい"
    end
  end

  private
  def messages_params
    params.require(:message).permit(:name, :image).merge(user_id: current_user.id, group_id: params[:group_id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @groups =current_user.groups
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE ?', "%#{params[:name]}%")
    respond_to do |format|
        format.json { render json: @users }
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def user_names(group)
    users = group.users
    users.pluck(:name).join(" ")
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/create.html.haml
%body
  .contents
    .menu
      .chat-user
        %h4 user-name
        .chat-user__icon
          =link_to new_group_path do
            =fa_icon "pencil-square-o"
          =link_to edit_user_registration_path do
            =fa_icon "cog"
      %ul.chat-groups
        %li.chat-group
          %p.chat-group__name テックキャンプ
          %p.chat-group__message aaa
    .main-screen
      .main-header
        .main-header--left
          %h2 group name
          %p.group-menbers Members: kyota
        .main-header--right
          %a.edit-btn Edit
      .main-body
        %ul.chat-messages
          %li.chat-message
            .chat-message__header.clearfix
              %p.chat-message__name aaa
              %p.chat-message__time  2017/02/23 12:12:12
            %p.chat-message__body  aaa
      .main-footer
        %form.new-message
          .main-footer__body
            %textarea.typing-box{placeholder: "type a message"}
            .main-footer__image
              =fa_icon "image"
            %input{type: "submit"}

app/views/groups/edit.html.haml
%body
  .chat-group-form
    %h1 チャットグループ編集
    = form_for @group do |f|
      - if @group.errors.any?
        #error_explanation.alert.alert-danger
          %h2= pluralize(@group.errors.count, "error")
          %ul
          - @group.errors.full_messages.each do |message|
            %li= message
      .chat-group-form__field.clearfix
        .chat-group-form__field--left
          %label.chat-group-form__label{:for => "chat_group_name"} グループ名
        .chat-group-form__field--right
          = f.text_field :name, placeholder: "グループ名を入力してください", class: "chat-group-form__input"
      / .chat-group-form__field.clearfix
      /   .chat-group-form__field--left
      /     %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      /   .chat-group-form__field--right
      /     .chat-group-form__search.clearfix
      /       %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      /     #user-search-result
      .chat-group-form__field.clearfix
        .chat-group-form__field--left
          %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
        .chat-group-form__field--right
          #chat-group-users
            #chat-group-user-22.chat-group-user.clearfix
              .check_box
                = f.collection_check_boxes(:user_ids, User.all, :id, :name) do |b|
                  = b.label { b.check_box + b.text }
      .chat-group-form__field.clearfix
        .chat-group-form__field--left
        .chat-group-form__field--right
          = f.submit "Save", class: "chat-group-form__action-btn"

app/views/groups/new.html.haml
%body
  .chat-group-form
    %h1 新規チャットグループ
    = form_for @group do |f|
      - if @group.errors.any?
        #error_explanation.alert.alert-danger
          %h2= pluralize(@group.errors.count, "error")
          %ul
          - @group.errors.full_messages.each do |message|
            %li= message
      .chat-group-form__field.clearfix
        .chat-group-form__field--left
          %label.chat-group-form__label{:for => "chat_group_name"} グループ名
        .chat-group-form__field--right
          = f.text_field :name, placeholder: "グループ名を入力してください", class: "chat-group-form__input"
      .chat-group-form__field.clearfix
        .chat-group-form__field--left
          %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
        .chat-group-form__field--right
          .chat-group-form__search.clearfix
            %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
          #user-search-result
      .chat-group-form__field.clearfix
        .chat-group-form__field--left
          %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
        .chat-group-form__field--right
          #chat-group-users
            #chat-group-user-22.chat-group-user.clearfix
              %ul#chat-group-users-added
                %li=current_user.name
                =hidden_field_tag "group[user_ids][]",current_user.id, id: "users-value"
      .chat-group-form__field.clearfix
        .chat-group-form__field--left
        .chat-group-form__field--right
          = f.submit "Save", class: "chat-group-form__action-btn"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if notice
      %p.alert-notice
        = notice
    - if alert
      %p.alert-error
        = alert
    = yield

app/views/message/home.html.haml
%body
  .contents
    .menu
      .chat-user
        %h4 user-name
        .chat-user__icon
          =fa_icon "pencil-square-o"
          =fa_icon "cog"
      %ul.chat-groups
        %li.chat-group
          %p.chat-group__name テックキャンプ
          %p.chat-group__message aaa
    .main-screen
      .main-header
        .main-header--left
          %h2 group name
          %p.group-menbers Members: kyota
        .main-header--right
          %a.edit-btn Edit
      .main-body
        %ul.chat-messages
          %li.chat-message
            .chat-message__header.clearfix
              %p.chat-message__name aaa
              %p.chat-message__time  2017/02/23 12:12:12
            %p.chat-message__body  aaa
      .main-footer
        %form.new-message
          .main-footer__body
            %textarea.typing-box{placeholder: "type a message"}
            .main-footer__image
              =fa_icon "image"
            %input{type: "submit"}

app/views/messages/index.html.haml
%body
  .contents
    .menu
      .chat-user
        %h4
          =current_user.name
        .chat-user__icon
          =link_to new_group_path do
            =fa_icon "pencil-square-o"
          =link_to edit_user_registration_path do
            =fa_icon "cog"
      - @groups.each do |group|
        %ul.chat-groups
          %li.chat-group
            = link_to group_messages_path(group) do
              %p.chat-group__name
                =group.name
              %p.chat-group__message aaa
    .main-screen
      .main-header
        .main-header--left
          %h2=@group.name
          %p.group-menbers Members: #{user_names(@group)}
        .main-header--right
          =link_to 'Edit', edit_group_path(@group), class: "edit-btn"
      .main-body
        - @group.messages.each do |message|
          %ul.chat-messages
            %li.chat-message
              .chat-message__header.clearfix
                %p.chat-message__name
                  =message.user.name
                %p.chat-message__time
                  =message.created_at
              %p.chat-message__body
                =message.name
              - if message.image.url.present?
                =image_tag message.image.url
      .main-footer
        = form_for [@group, @message] do |f|
          .main-footer__body
            = f.text_area :name, placeholder: "type a message", class: "typing-box"
            .main-footer__image
              %label
                =fa_icon "image"
                = f.file_field :image, style: "display: none"
            = f.submit "送信"

app/views/top/index.html.haml
%body
  .contents
    .menu
      .chat-user
        %h4
          =current_user.name
        .chat-user__icon
          =link_to new_group_path do
            =fa_icon "pencil-square-o"
          =link_to edit_user_registration_path do
            =fa_icon "cog"
      - @groups.each do |group|
        %ul.chat-groups
          %li.chat-group
            =link_to group_messages_path(group) do
              %p.chat-group__name
                =group.name
              %p.chat-group__message aaa
          / =link_to 'Edit', edit_group_path, class: "edit-b